version: '3.7'

services:
  game-client:
    container_name: game-client
    build:
      context: .
      dockerfile: IndividualProjFE\individprojfe\Dockerfile
    volumes:
      - '.:/IndividualProjFE/individprojfe/app'
      - '/IndividualProjFE/individprojfe/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  game-server:
    container_name: game-server
    build:
      context: .
      dockerfile: IndividualProjBE\Dockerfile
    ports:
      - 8080:8080